const { SlashCommandBuilder } = require("@discordjs/builders");
const connectDatabase = require("../middleware/mongodbConnector.js");
const User = require("../models/user.js");
const { findUuidInConversationReplies } = require("../middleware/mcmApi.js");
const resourcesJSON = require("../resources.json");
const { verifyUserResources } = require("../middleware/verifierMiddleware.js");
const { createEmbedded } = require("../middleware/embeddedUtils")

module.exports = {
  data: new SlashCommandBuilder()
    .setName("verify-code")
    .setDescription("Verify the code generated by starting a conversation!"),
  async execute(interaction) {
    const discordID = interaction.user.id;
    await connectDatabase();
    const userDatabase = await User.findOne({ discord_id: discordID });

    await interaction.reply({
      content: "Loading...",
      ephemeral: true,
    });

    if (!userDatabase) {
      await interaction.followUp({
        ephemeral: true,
        embeds: [createEmbedded(
          "You are not verified",
          "There is no data associated with this discord address. Please use the command **/verify-user** first",
          "#BD3838")],
      });
      return;
    }

    const mcmAccountAlreadyVerified = await User.findOne({
      mc_market_user_id: userDatabase.mc_market_user_id,
      verifiedDate: { $exists: true },
    });

    if (mcmAccountAlreadyVerified) {
      await interaction.followUp({
        ephemeral: true,
        embeds: [createEmbedded(
          "User already taken",
          "There is already a McMarket account verified for requested id",
          "#BD3838")],
      });
      return;
    }

    const { mc_market_user_id: userID, conversation_id, uuid } = userDatabase;
    const { success, error } = await findUuidInConversationReplies(
      conversation_id,
      userID,
      uuid
    );

    if (error && [404, 403].includes(error.status)) {
      await interaction.followUp({
        ephemeral: true,
        embeds: [createEmbedded(
          "Verification Code Not Found!",
          `
          Could not find a conversation with the generated code.\n
          If you already created an conversation, please try running this command later
          `,
          "#BD3838")],
      });
      return;
    }

    if (error) {
      await interaction.followUp({
        ephemeral: true,
        embeds: [createEmbedded(
          "Try again later",
          `There was an error on our side.`,
          "#BD3838")],
      });
      return;
    }

    if (!success) {
      await interaction.followUp({
        ephemeral: true,
        embeds: [createEmbedded(
          "Code couldn't be found..",
          "The code could not be found in conversation",
          "#BD3838")],
      });
      return;
    }

    addVerifiedRank(interaction);
    await verifyUserResources(
      resourcesJSON.resources,
      userDatabase,
      userID,
      interaction
    );

    userDatabase.verifiedDate = new Date();

    await userDatabase.save();
    await interaction.followUp({
      embeds: [createEmbedded(
        "Success!",
        `You have been successfully verified!`,
        "#47f066")],
      ephemeral: true
    });
  },
};

const addVerifiedRank = (interaction) => {
  if (!process.env.VERIFIED_USER_ROLE_ID) return;

  interaction.member.roles.add(process.env.VERIFIED_USER_ROLE_ID);
};
